### ISSUE TITLE
Make the README look fancy

### ISSUE THREAD

**Issue by EwanLyon** [ausspeedruns/ausspeedruns.com#11]
I love a fancy schmancy README. One with images and the sheilds.io stuff. I want to make people excited to try and help this project which involves making a really REALLY good first impression.

**Comment by Rishav1707** [comment]
Can you provide me with a brief introduction to this repo?
Some screenshots?
Usage of this repo?
Features of this project?

**Comment by EwanLyon** [comment]
If you're gonna do drive by repo help or have a bot scrape for issues on github at least look at the project before commenting.
